# Generated by Django 4.1.7 on 2023-04-29 14:24

import backend.storages
import ckeditor_uploader.fields
from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "english_version",
                    models.BooleanField(
                        default=False,
                        help_text="Εαν υπάρχει έκδοση στα αγγλικά, ενεργοποιήστε το.",
                    ),
                ),
                ("greek_title", models.CharField(max_length=150, unique=True)),
                (
                    "english_title",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("greek_slug", models.SlugField(allow_unicode=True, max_length=150)),
                (
                    "english_slug",
                    models.SlugField(blank=True, max_length=150, null=True),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        max_length=350,
                        storage=backend.storages.OverwriteStorage,
                        upload_to=news.models.News.get_image_path,
                    ),
                ),
                (
                    "mobile_thumbnail",
                    models.ImageField(
                        blank=True,
                        max_length=350,
                        null=True,
                        upload_to=news.models.News.get_image_path,
                    ),
                ),
                (
                    "greek_body",
                    ckeditor_uploader.fields.RichTextUploadingField(max_length=30000),
                ),
                (
                    "english_body",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True,
                        help_text="Η έκδοση του κειμένου στην Αγγλική γλώσσα.",
                        max_length=30000,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name_plural": "News",},
        ),
    ]
