# Generated by Django 4.1.7 on 2023-05-08 11:17

import backend.storages
from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="thumbnail",
            field=models.ImageField(
                help_text="Η εικόνα που θα ανεβάσετε να μην έχει το ίδιο όνομα με αυτή που είναι ανεβασμένη (αν υπάρχει ανεβασμένη εικόνα).",
                max_length=350,
                storage=backend.storages.OverwriteStorage,
                upload_to=news.models.News.get_image_path,
            ),
        ),
    ]
