# Generated by Django 4.1.7 on 2023-05-10 15:14

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="english_body",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True,
                help_text="Η έκδοση του κειμένου στην Αγγλική γλώσσα (έαν υπάρχει αγγλική έκδοση του κειμένου).",
                max_length=30000,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(
                fields=["english_version", "created_at"],
                name="news_news_english_39cf50_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(
                fields=["greek_slug"], name="news_news_greek_s_c1fe97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(
                fields=["english_version", "english_slug"],
                name="news_news_english_7a61e6_idx",
            ),
        ),
    ]
