# Generated by Django 4.1.7 on 2023-05-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_news_english_body_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="news", name="mobile_thumbnail",),
    ]
