# Generated by Django 4.1.7 on 2023-04-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("society", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subgroup",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
