# Generated by Django 4.1.7 on 2023-05-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("society", "0003_alter_subgroup_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="society",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="society",
            name="facebook",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="society",
            name="instagram",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="society",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="society",
            name="tiktok",
            field=models.URLField(blank=True, null=True),
        ),
    ]
