# Generated by Django 4.1.7 on 2023-05-07 21:21

import backend.storages
from django.db import migrations, models
import society.models


class Migration(migrations.Migration):

    dependencies = [
        ("society", "0004_society_email_society_facebook_society_instagram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subgroup",
            name="thumbnail",
            field=models.ImageField(
                max_length=350,
                storage=backend.storages.OverwriteStorage,
                upload_to=society.models.SubGroup.get_image_path,
            ),
        ),
    ]
