# Generated by Django 4.1.7 on 2023-05-08 11:17

import backend.storages
from django.db import migrations, models
import society.models


class Migration(migrations.Migration):

    dependencies = [
        ("society", "0005_alter_subgroup_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="society",
            name="recruitment_form",
            field=models.URLField(blank=True, help_text="Φόρμα πρόσληψης.", null=True),
        ),
        migrations.AlterField(
            model_name="society",
            name="logo",
            field=models.ImageField(
                help_text="Η εικόνα που θα ανεβάσετε να μην έχει το ίδιο όνομα με αυτή που είναι ανεβασμένη (αν υπάρχει ανεβασμένη εικόνα).",
                storage=backend.storages.OverwriteStorage,
                upload_to=society.models.Society.get_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="thumbnail",
            field=models.ImageField(
                help_text="Η εικόνα που θα ανεβάσετε να μην έχει το ίδιο όνομα με αυτή που είναι ανεβασμένη (αν υπάρχει ανεβασμένη εικόνα).",
                max_length=350,
                storage=backend.storages.OverwriteStorage,
                upload_to=society.models.SubGroup.get_image_path,
            ),
        ),
    ]
