# Generated by Django 4.1.7 on 2023-05-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("society", "0007_alter_society_page_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subgroup",
            name="english_body",
            field=models.TextField(help_text="450 characters maximum.", max_length=450),
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="greek_body",
            field=models.TextField(help_text="450 characters maximum.", max_length=450),
        ),
    ]
