# Generated by Django 4.1.7 on 2023-05-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("society", "0008_alter_subgroup_english_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subgroup",
            name="english_body",
            field=models.TextField(help_text="379 characters maximum.", max_length=379),
        ),
        migrations.AlterField(
            model_name="subgroup",
            name="greek_body",
            field=models.TextField(help_text="379 characters maximum.", max_length=379),
        ),
    ]
