# Generated by Django 4.1.7 on 2023-04-29 14:25

import backend.storages
import ckeditor_uploader.fields
from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("society", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "english_version",
                    models.BooleanField(
                        default=False,
                        help_text="Εαν έχει αγγλική έκδοση το Εvent ενεργοποίησε το.",
                    ),
                ),
                (
                    "greek_title",
                    models.CharField(
                        help_text="Ελληνικός τίτλος του Event",
                        max_length=150,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "english_title",
                    models.CharField(
                        blank=True,
                        help_text="Αγγλικός τίτλος του Event(εαν έχει αγγλική έκδοση)",
                        max_length=150,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "greek_slug",
                    models.SlugField(allow_unicode=True, max_length=150, unique=True),
                ),
                (
                    "english_slug",
                    models.SlugField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        max_length=350,
                        storage=backend.storages.OverwriteStorage,
                        upload_to=event.models.Event.get_image_path,
                    ),
                ),
                (
                    "mobile_thumbnail",
                    models.ImageField(
                        blank=True,
                        max_length=350,
                        null=True,
                        upload_to=event.models.Event.get_image_path,
                    ),
                ),
                (
                    "greek_body",
                    ckeditor_uploader.fields.RichTextUploadingField(max_length=30000),
                ),
                (
                    "english_body",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True,
                        help_text="Η έκδοση του κειμένου στην Αγγλική γλώσσα.",
                        max_length=30000,
                        null=True,
                    ),
                ),
                (
                    "greek_event_place",
                    models.CharField(default="NTUA Library", max_length=150),
                ),
                (
                    "english_event_place",
                    models.CharField(
                        blank=True, default="NTUA Library", max_length=150, null=True
                    ),
                ),
                ("event_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("societies", models.ManyToManyField(to="society.society")),
            ],
            options={"verbose_name_plural": "Events",},
        ),
    ]
