# Generated by Django 4.1.7 on 2023-05-10 15:14

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_alter_event_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="english_body",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True,
                help_text="Η έκδοση του κειμένου στην Αγγλική γλώσσα. (εαν υπάρχει αγγλική έκδοση του κειμένου)",
                max_length=30000,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["english_version", "event_time"],
                name="event_event_english_482bd7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["greek_slug"], name="event_event_greek_s_87167b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["english_version", "english_slug"],
                name="event_event_english_bd0316_idx",
            ),
        ),
    ]
