# Generated by Django 4.1.7 on 2023-04-29 14:22

import backend.storages
from django.db import migrations, models
import django.db.models.deletion
import people.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("society", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("role", models.CharField(max_length=200)),
                (
                    "profile_pic",
                    models.ImageField(
                        max_length=350,
                        storage=backend.storages.OverwriteStorage,
                        upload_to=people.models.Person.get_image_path,
                    ),
                ),
                (
                    "society",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="society.society",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "People",
                "unique_together": {("full_name", "society")},
            },
        ),
    ]
