# Generated by Django 4.1.7 on 2023-05-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0003_alter_person_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
