# Generated by Django 4.1.7 on 2023-05-07 21:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0004_alter_person_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
