# Generated by Django 4.1.7 on 2023-05-07 22:27

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0006_alter_person_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="random_number_after_name",
            field=models.IntegerField(
                default=people.models.random_number_generator, editable=False
            ),
        ),
    ]
