# Generated by Django 4.1.7 on 2023-05-08 11:17

import backend.storages
from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0007_person_random_number_after_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="profile_pic",
            field=models.ImageField(
                help_text="Η εικόνα που θα ανεβάσετε να μην έχει το ίδιο όνομα με αυτή που είναι ανεβασμένη (αν υπάρχει ανεβασμένη εικόνα).",
                max_length=350,
                storage=backend.storages.OverwriteStorage,
                upload_to=people.models.Person.get_image_path,
            ),
        ),
    ]
