# Generated by Django 4.1.7 on 2023-05-10 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0008_alter_person_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(model_name="person", name="full_name",),
        migrations.AddField(
            model_name="person",
            name="full_name_greek",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="Όνομα στα Ελληνικά.",
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
