# Generated by Django 4.1.7 on 2023-05-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0009_remove_person_full_name_person_full_name_greek"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="full_name_english",
            field=models.CharField(
                default="1", help_text="Όνομα στα Αγγλικά", max_length=200
            ),
        ),
    ]
