# Generated by Django 4.1.7 on 2023-05-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0010_person_full_name_english"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="full_name_english",
            field=models.CharField(help_text="Όνομα στα Αγγλικά", max_length=200),
        ),
    ]
