# Generated by Django 4.1.7 on 2023-05-05 00:34

import awards.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("society", "0003_alter_subgroup_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "year",
                    models.IntegerField(validators=[awards.models.year_validation]),
                ),
                (
                    "society",
                    models.ForeignKey(
                        blank=True,
                        help_text="Εαν το βραβειο το πήρε το SB αφήστε το κενό.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="society.society",
                    ),
                ),
            ],
        ),
    ]
